# Generated by Django 4.1.2 on 2022-11-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgs',
            field=models.ImageField(default=True, null=True, upload_to='media/'),
        ),
    ]
